# Generated by Django 4.0.2 on 2022-03-05 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot_id', models.CharField(max_length=4)),
                ('day', models.CharField(choices=[('sa', 'Saturday'), ('su', 'Sunday'), ('mo', 'Monday'), ('tu', 'Tuseday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday')], max_length=9)),
                ('start_hr', models.TimeField()),
                ('end_hr', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='TeachesId', serialize=False, to='users.instructor')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeachesCourseId', to='university.section')),
                ('sec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeachesSectionId', to='university.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachesSemester', to='university.section')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeachesYaer', to='university.section')),
            ],
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.student')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TakesCourseId', to='university.section')),
                ('sec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TakesSectionId', to='university.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TakesSemester', to='university.section')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TakesYear', to='university.section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SectionBuilding', to='university.classroom'),
        ),
        migrations.AddField(
            model_name='section',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course'),
        ),
        migrations.AddField(
            model_name='section',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SectionRoomNumber', to='university.classroom'),
        ),
        migrations.AddField(
            model_name='prereq',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Current', to='university.course'),
        ),
        migrations.AddField(
            model_name='prereq',
            name='prereq_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prereq', to='university.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.department'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='i_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.instructor'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
