# Generated by Django 4.0.2 on 2022-03-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='university.student', unique=True),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='TeachesId', serialize=False, to='university.instructor', unique=True),
        ),
    ]
