# Generated by Django 4.0.2 on 2022-03-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_instructor_options_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instructor',
            table='instructor',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
